networks:
  default:
    driver: bridge
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - default
    restart: always
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: patient_service
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - default
    restart: always
  discovery_service:
    build: ./discovery-service
    container_name: discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8761:8761"
    networks:
      - default
    restart: always
  patient_service:
    build: ./patient-service
    container_name: patient-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8100:8100"
    depends_on:
      - mysql
      - discovery_service
    networks:
      - default
    restart: always
  doctor_service:
    build: ./doctor-service
    container_name: doctor-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8200:8200"
    depends_on:
      - mongo
      - discovery_service
    networks:
      - default
    restart: always
  appointment_service:
    build: ./appointment-service
    container_name: appointment-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8300:8300"
    depends_on:
      - mysql
      - mongo
      - discovery_service
    networks:
      - default
    restart: always