spring:
  application:
    name: discovery-service
server:
  port: 8761
eureka:
  client:
    registry-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    prefer-ip-address: true